// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// BOXCOX
SEXP BOXCOX(arma::mat D, arma::umat A, arma::mat X1, int cmds_start = 1, int random_start = 0, int d = 3, double lambda = 1, double mu = 1, double nu = 0, double tau = 1, int niter = 1000, int sample_rate = 100);
RcppExport SEXP DimReduce_BOXCOX(SEXP DSEXP, SEXP ASEXP, SEXP X1SEXP, SEXP cmds_startSEXP, SEXP random_startSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP nuSEXP, SEXP tauSEXP, SEXP niterSEXP, SEXP sample_rateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    arma::mat D = Rcpp::as<arma::mat >(DSEXP);
    arma::umat A = Rcpp::as<arma::umat >(ASEXP);
    arma::mat X1 = Rcpp::as<arma::mat >(X1SEXP);
    int cmds_start = Rcpp::as<int >(cmds_startSEXP);
    int random_start = Rcpp::as<int >(random_startSEXP);
    int d = Rcpp::as<int >(dSEXP);
    double lambda = Rcpp::as<double >(lambdaSEXP);
    double mu = Rcpp::as<double >(muSEXP);
    double nu = Rcpp::as<double >(nuSEXP);
    double tau = Rcpp::as<double >(tauSEXP);
    int niter = Rcpp::as<int >(niterSEXP);
    int sample_rate = Rcpp::as<int >(sample_rateSEXP);
    SEXP __result = BOXCOX(D, A, X1, cmds_start, random_start, d, lambda, mu, nu, tau, niter, sample_rate);
    return Rcpp::wrap(__result);
END_RCPP
}
// cmds
SEXP cmds(arma::mat D, double d);
RcppExport SEXP DimReduce_cmds(SEXP DSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    arma::mat D = Rcpp::as<arma::mat >(DSEXP);
    double d = Rcpp::as<double >(dSEXP);
    SEXP __result = cmds(D, d);
    return Rcpp::wrap(__result);
END_RCPP
}
