// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// BOXCOX
SEXP BOXCOX(SEXP dist, SEXP adjacency, SEXP X1 = 0, int random_start = 1, int d = 3, double lambda = 1, double mu = 1, double nu = 0, double tau = 1, int niter = 1000);
RcppExport SEXP DimReduce_BOXCOX(SEXP distSEXP, SEXP adjacencySEXP, SEXP X1SEXP, SEXP random_startSEXP, SEXP dSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP nuSEXP, SEXP tauSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    SEXP dist = Rcpp::as<SEXP >(distSEXP);
    SEXP adjacency = Rcpp::as<SEXP >(adjacencySEXP);
    SEXP X1 = Rcpp::as<SEXP >(X1SEXP);
    int random_start = Rcpp::as<int >(random_startSEXP);
    int d = Rcpp::as<int >(dSEXP);
    double lambda = Rcpp::as<double >(lambdaSEXP);
    double mu = Rcpp::as<double >(muSEXP);
    double nu = Rcpp::as<double >(nuSEXP);
    double tau = Rcpp::as<double >(tauSEXP);
    int niter = Rcpp::as<int >(niterSEXP);
    SEXP __result = BOXCOX(dist, adjacency, X1, random_start, d, lambda, mu, nu, tau, niter);
    return Rcpp::wrap(__result);
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP DimReduce_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    List __result = rcpp_hello_world();
    return Rcpp::wrap(__result);
END_RCPP
}
