# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BOXCOX <- function(D, A, X1, cmds_start = 1L, random_start = 0L, d = 3L, lambda = 1, mu = 1, nu = 0, tau = 1, niter = 1000L, sample_rate = 100L, bfgs = 0L) {
    .Call('DimReduce_BOXCOX', PACKAGE = 'DimReduce', D, A, X1, cmds_start, random_start, d, lambda, mu, nu, tau, niter, sample_rate, bfgs)
}

cmds <- function(D, d) {
    .Call('DimReduce_cmds', PACKAGE = 'DimReduce', D, d)
}

