# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BOXCOX <- function(dist, adjacency, X1 = 0L, random_start = 1L, d = 3L, lambda = 1, mu = 1, nu = 0, tau = 1, niter = 1000L) {
    .Call('DimReduce_BOXCOX', PACKAGE = 'DimReduce', dist, adjacency, X1, random_start, d, lambda, mu, nu, tau, niter)
}

rcpp_hello_world <- function() {
    .Call('DimReduce_rcpp_hello_world', PACKAGE = 'DimReduce')
}

